name: Desplegar contenido estático en Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Instalar pnpm PRIMERO (antes de cualquier uso)
      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 2. Configurar Node.js (opcional, pero útil para versiones específicas)
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm" # Habilita cache para pnpm

      # 3. Instalar dependencias con pnpm
      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      # 4. Construir con pnpm
      - name: Construir
        run: pnpm run build

      # Pasos de despliegue (sin cambios)
      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
